spring:
  datasource:
    url: jdbc:postgresql://trackival-db:5432/trackival-master-data

#spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql

management:
  endpoints:
    web:
      exposure:
        include: "health, info"
