spring:
  application:
    name: trackival-service
  main:
    banner-mode: off
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5435/invoicesystem
    username: postgres
    password: password
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        connection:
          charSet: "UTF-8"
  jmx:
    enabled: false
  sql:
    init:
      platform: postgres
      mode: never
      encoding: UTF-8
  graphql:
    schema:
      printer:
        enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST
      max-age: 1800s
    graphiql:
      enabled: true

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: false

trackival:
  coordinate:
    api:
      key: "1e33fb53a6815e370fe01c1f8eacb57d"
      url: "http://api.positionstack.com/v1/forward?access_key=%API_KEY%&query=%QUERY%&limit=1&output=json"

#logging:
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%mdc] - %msg%n"
